### PR TITLE
Updated this to handle more than one character delimiters.

### PR DESCRIPTION
**Pull request by seeker25**
Also Commented out the \DEL sequence removal (this bug caused a random d to pop up in the file).

### CODE REVIEW

**Comment by gmddmg** [comment]
Just to be sure before accepting the pull request, as I won't have time to review soon: Did you run the examples included without issues, regardless of your particular use case? Thx!

**Comment by seeker25** [comment]
I'll give it a go and let you know, sorry lol.

**Comment by gmddmg** [comment]
Yeah, please do. Each one shows a differerent feature and uses different formats. They are not too many and it's the only way of doing regression test I have. Thx!

**Comment by seeker25** [comment]
They all worked.

**Pull request merged**
